name: Mirror Docker Image to ACR

on:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Pull images from Docker Hub
        run: |
          docker pull apache/seatunnel:2.3.8

      - name: Login to Aliyun ACR
        run: |
          docker login \
            -u ${{ secrets.ALI_REGISTRY_USER }} \
            -p ${{ secrets.ALI_REGISTRY_PWD }} \
            ${{ secrets.ALI_REGISTRY }}

      - name: Tag and Push to ACR
        run: |
          docker tag apache/seatunnel:2.3.8 ${{ secrets.ALI_REGISTRY }}/my-mirrors/seatunnel:2.3.8
          docker push ${{ secrets.ALI_REGISTRY }}/my-mirrors/seatunnel:2.3.8
          echo "✅ 全部推送完成！"
          echo "拉取命令1: docker pull ${{ secrets.ALI_REGISTRY }}/my-mirrors/seatunnel:2.3.8"
